name: login cloud providers
on:
    workflow_dispatch:
jobs:
    login:
      strategy:
        matrix:
          provider: ["AWS", "GCP"]
      runs-on: ubuntu-latest
      steps:
      - name: Login to Cloud
        uses: vinicius3516/repo-cd/.github/workflows/cd.yml@main
        with:
          provider: ${{ matrix.provider }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          gcp_creden: ${{ secrets.GCP_CREDEN }}
